server:
  port: 8081
  servlet:
    context-path: /api

spring:
  application:
    name: clarops-sr-engineer-challenge
  docker:
    compose:
      enabled: true
      file: ${DOCKER_COMPOSE_FILE:docker/docker-compose.yml}
      lifecycle-management: start-only
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/clarops_challenge}
    username: ${PG_USERNAME:clarops_user}
    password: ${PG_PASSWORD:clarops_pass}
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        type:
          json_format_mapper: com.clara.challenge.config.ToolsJacksonJsonFormatMapper
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    web:
      exposure:
        include: health,info,mappings
